Blog/ServiceHost/Areas/Administration/Pages/Accounts/Account/Index.cshtml.cs
using System.Collections.Generic;
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Account
{
    public class IndexModel : PageModel
    {
        [TempData] public string Message { get; set; }
        public AccountSearchModel SearchModel;
        public List<AccountViewModel> Accounts;
        private readonly IAccountApplication _accountApplication;
        private readonly IRoleApplication _roleApplication;
        public SelectList Roles;

        public IndexModel(IAccountApplication accountApplication, IRoleApplication roleApplication)
        {
            _accountApplication = accountApplication;
            _roleApplication = roleApplication;
        }


        public void OnGet(AccountSearchModel searchModel)
        {
            Roles = new SelectList(_roleApplication.List(), "Id", "Name");
            Accounts = _accountApplication.Search(searchModel);
        }

        public IActionResult OnGetRegister()
        {
            var command = new RegisterAccount
            {
                Roles = _roleApplication.List()
            };
            return Partial("./Register", command);
        }

        public JsonResult OnPostRegister(RegisterAccount command)
        {
            var result = _accountApplication.Register(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var account = _accountApplication.GetDetails(id);
            account.Roles = _roleApplication.List();
            return Partial("./Edit", account);
        }

        public JsonResult OnPostEdit(EditAccount command)
        {
            var result = _accountApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetChangePassword(long id)
        {
            var command = new ChangePassword {Id = id};
            return Partial("./ChangePassword", command);
        }

        public JsonResult OnPostChangePassword(ChangePassword command)
        {
            var result = _accountApplication.ChangePassword(command);
            return new JsonResult(result);
        }
    }
}

Blog/ServiceHost/Areas/Administration/Pages/Accounts/Role/Create.cshtml.cs
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class CreateModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;
        public CreateRole Command;

        public CreateModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPost(CreateRole command)
        {
            var result = _roleApplication.Create(command);
            return RedirectToPage("Index");
        }
    }
}

Blog/ServiceHost/Areas/Administration/Pages/Accounts/Role/Edit.cshtml.cs
using System.Collections.Generic;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class EditModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;
        public EditRole Command;
        public List<SelectListItem> Permissions = new List<SelectListItem>();

        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> exposers)
        {
            _roleApplication = roleApplication;
            _exposers = exposers;
        }

        public void OnGet(long id)
        {
            Command = _roleApplication.GetDetails(id);
            var permissions = new List<PermissionDto>();
            foreach (var exposer in _exposers)
            {
                var exposerPermissions = exposer.Expose();
                foreach (var (key, value) in exposerPermissions)
                {
                    permissions.AddRange(value);
                    var group = new SelectListGroup
                    {
                        Name = key
                    };
                    foreach (var permission in value)
                    {
                        var item = new SelectListItem(permission.Name, permission.Code.ToString())
                        {
                            Group = group
                        };

                        /*if (Command.MappedPermissions.Any(x => x.Code == permission.Code))
                            item.Selected = true;*/

                        Permissions.Add(item);
                    }
                }
            }
        }


        public IActionResult OnPost(EditRole command)
        {
            var result = _roleApplication.Edit(command);
            return RedirectToPage("Index");
        }
    }
}

Blog/ServiceHost/Areas/Administration/Pages/Accounts/Role/Index.cshtml.cs
using System.Collections.Generic;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class IndexModel : PageModel
    {
        [TempData] public string Message { get; set; }
        public List<RoleViewModel> Roles;
        private readonly IRoleApplication _roleApplication;

        public IndexModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {
            Roles = _roleApplication.List();
        }
    }
}

Blog/ServiceHost/Areas/Administration/Pages/Blog/ArticleCategories/Index.cshtml.cs
using System.Collections.Generic;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Blog.ArticleCategories
{
    public class IndexModel : PageModel
    {
        public ArticleCategorySearchModel SearchModel;
        public List<ArticleCategoryViewModel> ArticleCategory;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public IndexModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(ArticleCategorySearchModel searchModel)
        {
            ArticleCategory = _articleCategoryApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            return Partial("./Create", new CreateArticleCategory());
        }

        public JsonResult OnPostCreate(CreateArticleCategory command)
        {
            var result = _articleCategoryApplication.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var articleCategory = _articleCategoryApplication.GetDetails(id);
            return Partial("./Edit", articleCategory);
        }

        public JsonResult OnPostEdit(EditArticleCategory command)
        {
            var result = _articleCategoryApplication.Edit(command);
            return new JsonResult(result);
        }
    }
}

Blog/ServiceHost/Areas/Administration/Pages/Blog/Articles/Create.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class CreateModel : PageModel
    {
        private readonly IArticleCategoryApplication _articleCategoryApplication;
        private readonly IArticleApplication _articleApplication;
        public SelectList ArticleCategories;
        public CreateArticle Command;

        public CreateModel(IArticleCategoryApplication articleCategoryApplication,
            IArticleApplication articleApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
            _articleApplication = articleApplication;
        }

        public void OnGet()
        {
            ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(),
                "Id", "Name");
        }

        public IActionResult OnPost(CreateArticle command)
        {
            var result = _articleApplication.Create(command);
            return RedirectToPage("./Index");
        }
    }
}

Blog/ServiceHost/Areas/Administration/Pages/Blog/Articles/Edit.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class EditModel : PageModel
    {
        private readonly IArticleCategoryApplication _articleCategoryApplication;
        private readonly IArticleApplication _articleApplication;
        public SelectList ArticleCategories;
        public EditArticle Command;

        public EditModel(IArticleCategoryApplication articleCategoryApplication,
            IArticleApplication articleApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
            _articleApplication = articleApplication;
        }

        public void OnGet(long id)
        {
            Command = _articleApplication.GetDetails(id);
            ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(),
                "Id", "Name");
        }

        public IActionResult OnPost(EditArticle command)
        {
            var result = _articleApplication.Edit(command);
            return RedirectToPage("./Index", result);
        }
    }
}

Blog/ServiceHost/Areas/Administration/Pages/Blog/Articles/Index.cshtml.cs
using System.Collections.Generic;
using _0_Framework.Infrastructure;
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    [Authorize(Roles = Roles.Administrator)]
    public class IndexModel : PageModel
    {
        public ArticleSearchModel SearchModel;
        public List<ArticleViewModel> Articles;
        public SelectList ArticleCategories;

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public IndexModel(IArticleCategoryApplication articleCategoryApplication,
            IArticleApplication articleApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
            _articleApplication = articleApplication;
        }

        public void OnGet(ArticleSearchModel searchModel)
        {
            ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(),
                "Id", "Name");
            Articles = _articleApplication.Search(searchModel);
        }
    }
}

Blog/ServiceHost/Pages/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Blog/ServiceHost/Pages/Account.cshtml.cs
using AccountManagement.Application.Contracts.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class AccountModel : PageModel
    {
        [TempData] public string LoginMessage { get; set; }
        [TempData] public string RegisterMessage { get; set; }
        private readonly IAccountApplication _accountApplication;

        public AccountModel(IAccountApplication accountApplication)
        {
            _accountApplication = accountApplication;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPostLogin(Login command)
        {
            var result = _accountApplication.Login(command);

            if (result.IsSucceeded)
                return RedirectToPage("/Index");

            LoginMessage = result.Message;
            return RedirectToPage("/Account");
        }

        public IActionResult OnGetLogout()
        {
            _accountApplication.Logout();
            return RedirectToPage("/Index");
        }

        public IActionResult OnPostRegister(RegisterAccount command, Login loginCommand)
        {
            var result = _accountApplication.Register(command);

            if (result.IsSucceeded)
            {
                _accountApplication.Login(loginCommand);
                return RedirectToPage("/Index");
            }

            RegisterMessage = result.Message;
            return RedirectToPage("/Account");
        }
    }
}

Blog/ServiceHost/Pages/Article.cshtml.cs
using System.Collections.Generic;
using _01_BlogQuery.Contracts.Article;
using CommentManagement.Application.Contracts.Comment;
using CommentManagement.Infrastructure.EfCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class ArticleModel : PageModel
    {
        public ArticleQueryModel Article;
        public List<ArticleQueryModel> LatestArticles;
        private readonly IArticleQuery _articleQuery;
        private readonly ICommentApplication _commentApplication;

        public ArticleModel(IArticleQuery articleQuery, ICommentApplication commentApplication)
        {
            _articleQuery = articleQuery;
            _commentApplication = commentApplication;
        }

        public void OnGet(string id)
        {
            Article = _articleQuery.GetArticleDetails(id);
            LatestArticles = _articleQuery.LatestArticles();
        }

        public IActionResult OnPost(AddComment command, string articleSlug)
        {
            command.Type = CommentType.Article;
            var result = _commentApplication.Add(command);
            return RedirectToPage("/Article", new {Id = articleSlug});
        }
    }
}

Blog/ServiceHost/Pages/ArticleCategory.cshtml.cs
using System.Collections.Generic;
using _01_BlogQuery.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class ArticleCategoryModel : PageModel
    {
        private readonly IArticleCategoryQuery _articleCategoryQuery;
        public List<ArticleCategoryQueryModel> ArticleCategories;

        public ArticleCategoryModel(IArticleCategoryQuery articleCategoryQuery)
        {
            _articleCategoryQuery = articleCategoryQuery;
        }

        public void OnGet()
        {
            ArticleCategories = _articleCategoryQuery.GetArticleCategories();
        }
    }
}

Blog/ServiceHost/Pages/Articles.cshtml.cs
using System.Collections.Generic;
using _01_BlogQuery.Contracts.Article;
using _01_BlogQuery.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class ArticlesModel : PageModel
    {
        private readonly IArticleQuery _articleQuery;
        private readonly IArticleCategoryQuery _articleCategoryQuery;
        public List<ArticleQueryModel> Articles;
        public List<ArticleCategoryQueryModel> ArticleCategories;
        public ArticleCategoryQueryModel ArticleCategory;

        public ArticlesModel(IArticleQuery articleQuery, IArticleCategoryQuery articleCategoryQuery)
        {
            _articleQuery = articleQuery;
            _articleCategoryQuery = articleCategoryQuery;
            Articles = new List<ArticleQueryModel>();
        }

        public void OnGet(string id)
        {
            ArticleCategories = _articleCategoryQuery.GetArticleCategories();
            Articles = _articleQuery.ArticlesBy(id);
        }
    }
}

Blog/ServiceHost/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ServiceHost.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Blog/ServiceHost/ViewComponents/LatestArticlesViewComponent.cs
using _01_BlogQuery.Contracts.Article;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class LatestArticlesViewComponent : ViewComponent
    {
        private readonly IArticleQuery _articleQuery;

        public LatestArticlesViewComponent(IArticleQuery articleQuery)
        {
            _articleQuery = articleQuery;
        }

        public IViewComponentResult Invoke()
        {
            var articles = _articleQuery.LatestArticles();
            return View(articles);
        }
    }
}

Blog/ServiceHost/Pages/AccessDenied.cshtml
@page
@model ServiceHost.Pages.AccessDeniedModel
@{
}

<h1>Sorry you dont have access to this page!</h1>

Blog/ServiceHost/Pages/Account.cshtml
@page
@model ServiceHost.Pages.AccountModel
@{
    ViewData["Title"] = "ورود و ثبت نام";
}

<section id="page-title" class="page-title-parallax page-title-center text-dark" style="background-image: url(~/Theme/assets/images/parallax/page-title-parallax.jpg);">
    <div class="container">
        <div class="page-title col-md-8" data-animation="fadeInDown" data-animation-delay="300">
            <h1>ورود/ثبت نام</h1>
        </div>
        <div class="breadcrumb col-md-4" data-animation="fadeInDown" data-animation-delay="800">
            <ul>
                <li>
                    <a asp-page="./Index">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li>
                    <a asp-page="./Index">خانه</a>
                </li>
                <li class="active">
                    <a asp-page="./Account">عضویت</a>
                </li>
            </ul>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h3 class="text-uppercase">ثبت نام</h3>
                <div class="m-t-30">
                    @if (Model.RegisterMessage != null)
                    {
                        <div class="alert alert-danger">@Model.RegisterMessage</div>
                    }
                    <form method="post" asp-page-handler="Register">
                        <div class="row">
                            <div class="form-group col-sm-6">
                                <label for="name">نام کامل</label>
                                <input type="text" aria-required="true" name="fullname" class="form-control
                                       required name" placeholder="نام و نام خانوادگی خود را وارد کنید">
                            </div>
                            <div class="form-group col-sm-6">
                                <label for="mobile">موبایل</label>
                                <input type="text" aria-required="true" name="mobile" class="form-control
                                       required" placeholder="شماره تماس خود را وارد کنید">
                            </div>
                            <div class="form-group col-sm-12">
                                <label for="name">نام کاربری</label>
                                <input type="text" aria-required="true" name="username" class="form-control
                                       required name" placeholder="نام کاربری خود را وارد کنید">
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-sm-6">
                                <label for="subject">رمز عبور</label>
                                <input type="password" name="password" class="form-control required"
                                       placeholder="رمز عبور را وارد کنید">
                            </div>
                            <div class="form-group col-sm-6">
                                <label for="subject">تکرار رمز عبور</label>
                                <input type="password" name="repassword" class="form-control required"
                                       placeholder="تکرار رمز عبور را وارد کنید">
                            </div>
                        </div>
                        <input type="text" class="hidden" id="widget-contact-form-antispam" name="widget-contact-form-antispam" value="" />
                        <button class="btn btn-primary" type="submit">ثبت نام</button>
                    </form>
                </div>
            </div>

            <div class="col-md-6" style="right: 200px;">
                <h3 class="text-uppercase">ورود</h3>
                <div class="m-t-30">
                    @if (Model.LoginMessage != null)
                    {
                        <div class="alert alert-danger">@Model.LoginMessage</div>
                    }
                    <form id="widget-contact-form" role="form" method="post" asp-page-handler="Login">
                        <div class="row">
                            <div class="form-group col-sm-6">
                                <label for="name">نام کاربری</label>
                                <input type="text" aria-required="true" name="username" class="form-control
                                       required name" placeholder="نام کاربری خود را وارد کنید">
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-sm-6">
                                <label for="subject">رمز عبور</label>
                                <input type="password" name="password" class="form-control required"
                                       placeholder="رمز عبور را وارد کنید">
                            </div>
                        </div>
                        <input type="text" class="hidden" id="widget-contact-form-antispam" name="widget-contact-form-antispam" value="" />
                        <button class="btn btn-primary" type="submit" id="form-submit">ورود</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

Blog/ServiceHost/Pages/ArticleCategory.cshtml
@page "{id?}"
@model ServiceHost.Pages.ArticleCategoryModel
@{
    ViewData["Title"] = "مقالات";
}

<section id="page-title" class="page-title-parallax page-title-center text-dark"
         style="background-image:url(~/Theme/assets/images/parallax/page-title-parallax.jpg);">
    <div class="container">
        <div class="page-title col-md-8">
            <h1>گروه مقالات</h1>
        </div>
        <div class="breadcrumb col-md-4">
            <ul>
                <li>
                    <a asp-page="./Index">خانه</a>
                </li>
            </ul>
        </div>
    </div>
</section>
<section class="content">
    <div class="container">
        <div class="row">
            <div class="post-content post-modern post-content-single col-md-9">
                @foreach (var articleCategory in Model.ArticleCategories)
                {
                    <div class="post-item">
                        <div class="post-image">
                            <a asp-page="/Articles" asp-route-id="@articleCategory.Slug">
                                <img alt="@articleCategory.PictureAlt" src="~/Theme/assets/images/blog/@articleCategory.Picture"
                                     title="@articleCategory.PictureTitle">
                            </a>
                        </div>
                        <div class="post-content-details">
                            <div class="post-title">
                                <h2>@articleCategory.Name</h2>
                            </div>
                            <div class="post-description">
                                <p>@Html.Raw(articleCategory.Description)</p>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="sidebar sidebar-modern col-md-3">
                <div class="widget clearfix widget-contact-us" style="background-image: url('~/Theme/assets/images/world-map.png');background-position: 50% 55px; background-repeat: no-repeat">
                    <h4 class="widget-title">ارتباط با من</h4>
                    <ul class="list-large list-icons">
                        <li>
                            @*<i class="fa fa-phone"></i>*@
                            <strong>موبایل:</strong> 09339614483
                        </li>
                        <li>
                            @*<i class="fa fa-envelope"></i>*@
                            <strong>ایمیل:</strong> <a href="mailto:alirezapakravan111@gmail.com">alirezapakravan111@gmial.com</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

Blog/ServiceHost/Pages/Articles.cshtml
@page "{id}"
@model ServiceHost.Pages.ArticlesModel
@{
    ViewData["Title"] = "مقالات";
}

<section id="page-title" class="page-title-parallax page-title-center text-dark"
         style="background-image: url(~/Theme/assets/images/parallax/page-title-parallax.jpg);">
    <div class="container">
        <div class="page-title col-md-8">
            @foreach (var category in Model.Articles)
            {
                <h1>مقالات گروه: @category.CategoryName</h1>
                break;
            }
        </div>
        <div class="breadcrumb col-md-4">
            <ul>
                <li>
                    <a asp-page="./Index">خانه</a>
                </li>
                <li>
                    <a asp-page="/ArticleCategory">
                        گروه مقاله
                    </a>
                </li>
            </ul>
        </div>
    </div>
</section>
<section class="content">
    <div class="container">
        <div class="row">
            <div class="post-content post-modern col-md-9">
                @foreach (var article in Model.Articles)
                {
                    <div class="post-item">
                        <div class="post-image">
                            <a asp-page="./Article" asp-route-id="@article.Slug">
                                <img alt="@article.PictureAlt" title="@article.Title" src="~/Theme/assets/images/blog/@article.Picture">
                            </a>
                        </div>
                        <div class="post-content-details">
                            <div class="post-title">
                                <h3>
                                    <a asp-page="./Article" asp-route-id="@article.Slug">@article.Title</a>
                                </h3>
                            </div>
                            <div class="post-description">
                                <p>@article.ShortDescription</p>
                                <div class="post-read-more">
                                    <a class="read-more" asp-page="./Article" asp-route-id="@article.Slug">
                                        بیشتر بخوانید
                                        <i class="fa fa-long-arrow-right"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                }

                <div class="text-center">
                    <div class="pagination-wrap">
                        <ul class="pagination">
                            <li>
                                <a aria-label="Previous" href="#">
                                    <span aria-hidden="true">
                                        <i class="fa fa-angle-left"></i>
                                    </span>

                                </a>
                            </li>
                            <li>
                                <a href="#">1</a>
                            </li>
                            <li>
                                <a href="#">2</a>
                            </li>
                            <li>
                                <a href="#">3</a>
                            </li>
                            <li>
                                <a href="#">4</a>
                            </li>
                            <li>
                                <a href="#">5</a>
                            </li>
                            <li>
                                <a aria-label="Next" href="#">
                                    <span aria-hidden="true">
                                        <i class="fa fa-angle-right"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="sidebar sidebar-modern col-md-3">
                <div class="widget clearfix widget-contact-us" style="background-image: url('~/Theme/assets/images/world-map.png');background-position: 50% 55px; background-repeat: no-repeat">
                    <h4 class="widget-title">ارتباط با من</h4>
                    <ul class="list-large list-icons">
                        <li>
                            @*<i class="fa fa-phone"></i>*@
                            <strong>موبایل:</strong> 09339614483
                        </li>
                        <li>
                            @*<i class="fa fa-envelope"></i>*@
                            <strong>ایمیل:</strong> <a href="mailto:alirezapakravan111@gmail.com">alirezapakravan111@gmial.com</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

Blog/ServiceHost/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "صفحه ی اصلی";
}


@await Component.InvokeAsync("LatestArticles")